name: Deploy on environment
run-name: Deploy application onto specified environment
on:
  workflow_call:
    inputs:
        environment:
          required: true
          type: string
jobs:
  deploy:
    name: Deploy ${{ inputs.environment }} environment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Download lamnda function artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_${{ github.run_id }}
          path: ./.dist/
      - name: Download infrastructure artifacts
        uses: actions/download-artifact@v4
        with:
          name: infrastructure_${{ github.run_id }}
          path: ./infrastructure/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::662642131450:role/GitHub
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1
      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init
      - name: Select Workspace
        working-directory: ./infrastructure
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
      - name: Terraform Apply
        working-directory: ./infrastructure
        run: terraform apply -auto-approve
    
