name: GitHub Actions Demo
run-name: Generate and Present Data CI/CD pipeline
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Copying infrastructure folder to artifacts
        run: cp -R infrastructure .dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./.dist/*
          retention-days: 5
  deploy-dev:
    name: Deploy DEV environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::662642131450:role/GitHub
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1
      - name: Terraform Init
        working-directory: ./artifact/infrastructure
        run: terraform init
      - name: Select Workspace
        working-directory: ./artifact/infrastructure
        run: terraform workspace select dev
      - name: Terraform Plan
        working-directory: ./artifact/infrastructure
        run: terraform plan
    
