name: GitHub Actions Generate and Present Data
run-name: Generate and Present Data CI/CD pipeline
on: [push]
jobs:
  build_data_api_authorizer_fa:
    uses: ./.github/workflows/build.yml
    with:
      lambdaFunction: data_api_authorizer_fa
  build_data_generator_fa:
    uses: ./.github/workflows/build.yml
    with:
      lambdaFunction: data_generator_fa
  build_data_persister_fa:
    uses: ./.github/workflows/build.yml
    with:
      lambdaFunction: data_persister_fa
  build_data_presenter_fa:
    uses: ./.github/workflows/build.yml
    with:
      lambdaFunction: data_presenter_fa
  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4     
      - name: Upload infrastructure artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./infrastructure/
          retention-days: 1
          name: infrastructure_${{ github.run_id }}
  deploy-dev:
    uses: ./.github/workflows/deployment.yml
    needs: 
      - build_data_api_authorizer_fa
      - build_data_generator_fa
      - build_data_persister_fa
      - build_data_presenter_fa
      - infrastructure
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::662642131450:role/GitHub
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1
      - name: Run Integration Test
        working-directory: ./integration_tests
        run: ./integrationTest.sh
  deploy-prd:
    uses: ./.github/workflows/deployment.yml
    needs: integration-test
    permissions:
      id-token: write
      contents: read
    with:
      environment: prd