name: GitHub Actions Generate and Present Data
run-name: Generate and Present Data CI/CD pipeline
on: [push]
jobs:
  build_data_api_authorizer:
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      contents: read
    with:
      lambdaFunction: data_api_authorizer_fa
  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    needs: build_data_api_authorizer
    steps:     
      - name: Upload infrastructure artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./infrastructure/
          retention-days: 1
          name: infrastructure_${{ github.run_id }}
  deploy-dev:
    uses: ./.github/workflows/deployment.yml
    needs: infrastructure
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
  deploy-prd:
    uses: ./.github/workflows/deployment.yml
    needs: deploy-dev
    permissions:
      id-token: write
      contents: read
    with:
      environment: prd