name: GitHub Actions Demo
run-name: Generate and Present Data CI/CD pipeline
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./.dist/*.zip
          retention-days: 5