name: GitHub Actions Generate and Present Data
run-name: Generate and Present Data CI/CD pipeline
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Upload lambda function artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./.dist/
          retention-days: 1
          name: build_${{ github.run_id }}
      - name: Upload infrastructure artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./infrastructure/
          retention-days: 1
          name: infrastructure_${{ github.run_id }}
  deploy-dev:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: dev